### ISSUE TITLE
Style animations/transitions

### ISSUE THREAD

**Issue by IgorKrupenja** [igor-krupenja/zaino#163]
- [ ] modal open
- [x] Select popover close, should be off - simple approach with assigning `no-display` class did not work. also maybe replace with animation? https://stackoverflow.com/a/39669911/7405507
- [ ] error text appearing when there are errors in ItemForm
- [ ] Make sure that animation speeds are consistent
- [x] Github logo on log in page: requires Illustrator work (puppet warp tool)

for labels:
- [ ] https://lh3.googleusercontent.com/kXJgwc3Xv0zxP0cRFpz1-VeDsJShkOm8cQ6Xjz3gXAjCWAv2CUH7ho3cT7z0GeE-mtbJP5nNq0T1uzNXzbkOYdtbglHyLwDJ91zdpg=w1064-v0
- [ ] https://github.com/JedWatson/react-select/issues/2152#issuecomment-470889515
- [ ] https://css-tricks.com/float-labels-css/

example for modal open:
```css
.ReactModal__Overlay {
  opacity: 0;
  transform: translateX(-100px);
  transition: all 300ms ease-in-out;
}

.ReactModal__Overlay--after-open {
  opacity: 1;
  transform: translateX(0px);
}

.ReactModal__Overlay--before-close {
  opacity: 0;
  transform: translateX(-100px);
}
```
