### ISSUE TITLE
Style temp logo

### ISSUE THREAD

**Issue by IgorKrupenja** [igor-krupenja/zaino#183]
```css
#circle {
    background: #f00;
    width: 200px;
    height: 200px;
    border-radius: 50%;
}
```
